# Generated by Django 2.2.5 on 2020-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201130_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cardExpMonth',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cardExpYear',
            field=models.CharField(max_length=4),
        ),
    ]
