# Generated by Django 2.2.5 on 2020-11-30 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complain_type', models.CharField(max_length=100)),
                ('room_number', models.IntegerField(default=0)),
                ('employee_ID', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('complain_message', models.CharField(max_length=100)),
                ('solved_message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='types_of_complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
            ],
        ),
    ]
