# Generated by Django 2.2.5 on 2020-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('e_PW', models.CharField(max_length=20)),
                ('e_name', models.CharField(default='-', max_length=20)),
                ('e_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('e_work_type', models.CharField(blank=True, choices=[('houseman', 'Houseman'), ('londry', 'Londry'), ('operator', 'Operator'), ('reception', 'Reception'), ('reservation', 'Reservation'), ('roommaid', 'Room maid'), ('other', 'Other')], max_length=20)),
                ('e_birthdate', models.DateField(blank=True, null=True)),
                ('e_address', models.CharField(default='-', max_length=200)),
                ('e_salary', models.IntegerField(blank=True, default=0, null=True)),
                ('e_phone_number', models.CharField(default='000-0000-0000', max_length=100)),
            ],
        ),
    ]
