# Generated by Django 2.2.5 on 2020-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, upload_to='avators'),
        ),
    ]
